# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de venta')),
                ('tipo_arreglo', models.CharField(max_length=300, verbose_name='Tipo de arrelo')),
                ('nombre_fallecido', models.CharField(max_length=300, verbose_name='Fallecido')),
                ('cantidad_arreglos', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('cliente', models.CharField(max_length=300, verbose_name='Pedido por')),
                ('valor_total', models.IntegerField(verbose_name='Valor')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidanueva.Cliente')),
            ],
        ),
    ]
