# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidanueva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_arreglo',
            field=models.CharField(max_length=300, verbose_name='Tipo de arreglo'),
        ),
    ]
