# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidanueva', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='TipoCliente',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de venta'),
        ),
    ]
